# fly.toml app configuration file generated for cryptohack-discord-bot on 2025-11-23T06:46:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cryptohack-discord-bot'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile"

[env]
  CHECK_INTERVAL_MINUTES = '3'

[processes]
  app = 'python bot.py'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
